name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build (release)
      run: make release
    - name: Build (debug)
      run: make debug
    - name: Run tests
      run: make check || true
